module.exports = {
    "appearance": require('./appearance.js'),
    "bank": require('./bank.js'),
    "chat": require('./chat.js'),
    "combat-style": require('./combat-style.js'),
    "command": require('./command.js'),
    "duel": require('./duel.js'),
    "follow": require('./follow.js'),
    "game-object": require('./game-object.js'),
    "inventory": require('./inventory.js'),
    "known-players": require('./known-players.js'),
    "login": require('./login.js'),
    "logout": require('./logout.js'),
    "npc": require('./npc.js'),
    "option": require('./option.js'),
    "ping": require('./ping.js'),
    "player": require('./player.js'),
    "prayer": require('./prayer.js'),
    "register": require('./register.js'),
    "settings": require('./settings.js'),
    "shop": require('./shop.js'),
    "sleep": require('./sleep.js'),
    "social": require('./social.js'),
    "trade": require('./trade.js'),
    "walk": require('./walk.js'),
    "wall-object": require('./wall-object.js'),
};
